services:
  - type: web
    name: meal-planner
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py check --deploy
      gunicorn mealplanner.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: meal-planner-db
          property: connectionString
      - key: PORT
        value: 8000
      - key: DJANGO_SETTINGS_MODULE
        value: mealplanner.settings

databases:
  - name: meal-planner-db
    databaseName: meal_planner
    user: meal_planner 