services:
  - type: web
    name: meal-planner
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn mealplanner.wsgi:application --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: DEBUG
        value: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: meal-planner-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: mealplanner.settings

databases:
  - name: meal-planner-db
    plan: free 