services:
  - type: web
    name: meal-planner
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn mealplanner.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: meal-planner-db
          property: connectionString

databases:
  - name: meal-planner-db
    databaseName: meal_planner
    user: meal_planner 