# Generated by Django 5.0.2 on 2024-12-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Millitmetters'), ('l', 'Liter'), ('cup', 'Cups'), ('tbsp', 'Tablespoons'), ('piece', 'Pieces')], default='g', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(help_text='Time in minutes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(help_text='Time in minutes'),
        ),
    ]
