# Generated by Django 5.0.2 on 2024-12-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredients_unit_alter_recipe_cook_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, help_text='Enter an URL of your recipe image', max_length=1000),
        ),
    ]
