# Generated by Django 5.0.2 on 2024-12-31 04:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealplan',
            options={'ordering': ['time', 'meal_type']},
        ),
        migrations.AddField(
            model_name='mealplan',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='servings',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='mealplan',
            unique_together={('user', 'time', 'meal_type')},
        ),
    ]
